# Generated by Django 3.0.4 on 2020-03-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issue_department', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('issue_creation_date', models.DateTimeField()),
                ('is_this_new_ticket', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department')),
            ],
        ),
    ]
