# Generated by Django 3.0.4 on 2020-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_department_departmentroles_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_this_new_ticket',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_creation_date',
            field=models.TextField(max_length=100),
        ),
    ]
